preIncludeItems = ["title_group"]

[curriculum_templates]
org = "coding-minds"

[curriculum_templates.templates]
unity = "Templates used as part of Unity curriculum."
colab = "Some Google Colab notebooks for teaching concepts in Python."

[[curriculum_templates.unity_templates]]
name = "Unity 2 - Old Platforming Template"
link = "https://github.com/SurajSSingh/Unity-2-Platforming-Game"
summary = "Template to help guide with developing a 2D Platformer. Used to help teach how to use Unity's tilemap system, understand 2D physics, and save data across levels."

[[curriculum_templates.unity_templates]]
name = "Unity 2 - RTS Template"
link = "https://github.com/SurajSSingh/Unity_2_RTS_Game"
summary = "A simple RTS template to provide scaffolding for learning about inheritance and polymorphism."

[[curriculum_templates.unity_templates]]
name = "Unity 2 - Tower Defense Template"
link = "https://github.com/SurajSSingh/Unity-2-Tower-Defense-Template"
summary = "A simple tower defense game used to help teach Unity's scriptable object. Modified from the Unity 2 RTS project to reduce the number of things students need to learn about the template and replaces it in the curriculum."

[[curriculum_templates.unity_templates]]
name = "Unity 2 - New Platforming Template"
link = "https://github.com/SurajSSingh/Unity-2-Platforming-Template"
summary = "An updated 2D platform for Unity 2, focusing on improving /assets and clearer lesson flow."

[[curriculum_templates.unity_templates]]
name = "Unity 2 - Module 3 Exercises"
link = "https://github.com/SurajSSingh/Unity-2-Module-3---Unity-Exercises"
summary = "5 exercise scenes to help reinforce Unity concepts learned. Each exercise is a mini-game, including a UI-only guess the number game, 3D cannonball simulator, and 3D platformer."

[[curriculum_templates.unity_templates]]
name = "Unity 3 - Module 1 Obstacle Course"
link = "https://github.com/SurajSSingh/Obstacle-Course-Project"
summary = "A simple 3D obstacle course that is used to teach Unity' new Input System and local computer multiplayer."

[[curriculum_templates.unity_templates]]
name = "Unity 3 - Multiplayer Pong Template"
link = "https://github.com/SurajSSingh/MultiplayerPongTemplate"
summary = "A simple Pong setup framework to help teach multiplayer using Unity's Netcode for GameObjects."

[[curriculum_templates.unity_templates]]
name = "Unity 3 - Steam NGO Example"
link = "https://github.com/SurajSSingh/Steam_NGO_Example"
summary = "A set of scenes showing how to combine Steam and Unity's Netcode for GameObject."

[[curriculum_templates.unity_templates]]
name = "Unity 4 - ML-Agents Example"
link = "https://github.com/SurajSSingh/ML-Agents-Example"
summary = "A set of prefabs and scripts used to bootstrap working with [Unity's ML-Agents package](https://unity.com/products/machine-learning-agent)."

[[curriculum_templates.colab_templates]]
name = "Blockchain Example"
link = "https://colab.research.google.com/drive/1x5A8c0nUoT0QhEjQWgMaQ5_7xYCpTE5V?usp=sharing"
summary = "A very simple Python example of implementing a blockchain"

[[curriculum_templates.colab_templates]]
name = "Q-Learning Example"
link = "https://colab.research.google.com/drive/1oQ8PATtrhJaEBZnUlIPViCH05cnMr7Th"
summary = "A Python notebook going over how to use Q-Learning in OpenAI Gym"

[mentored]
org="coding-minds"

[[mentored.student_project]]
link="https://store.steampowered.com/app/1501920/Toewr_le_Fence__REMASTERED_coming_prob_not_soon/"
name="Toewr_le_Fence"
image="https://cdn.cloudflare.steamstatic.com/steam/apps/1501920/header.jpg?t=1677113417"
alt="Toewr_le_Fence Logo"
summary="A 3D/2D tower defense game using memes as the theme. Available on Steam."
org="coding-minds"
student="Andy Jia"
student_page="https://www.toewrlefence.com"

[[mentored.student_project]]
link="https://store.steampowered.com/app/1547630/Bridge2Code/"
name="Bridge2Code"
image="https://cdn.cloudflare.steamstatic.com/steam/apps/1547630/header.jpg?t=1618877916"
alt="Bridge2Code Logo"
summary="A 2D puzzle game where one writes a script to build a bridge. Available on <a href='https://ihdfbisblncselzkx.itch.io/bridge2code'>Itch.io</a> and Steam."
org="coding-minds"
student="Damon Wang"
student_github="https://github.com/D-a-m-o-n"

[[mentored.student_project]]
link="https://cchristinafu.github.io/Program1-Website/"
name="StemSisters Program-1"
image="/assets/images/stem-sister.png"
alt="Program 1 screenshot"
summary="A 2D coding farming that helps teach students about coding."
org="coding-minds"
student="Christina Fu"
student_github="https://github.com/cchristinafu"

[[mentored.student_project]]
link="https://play.google.com/store/apps/details/Pawdometer_Match_the_Dogs?id=com.Pawdometer.MatchProject&gl=US"
name="Pawdometer: Match the Dogs"
image="/assets/images/mtd-logo.png"
alt="Pawdometer: Match The Dog Logo"
summary="A match 4-game with dog theming and with integration with a sibling app to monitor dog steps. Available on the Google Play store."
org="coding-minds"
student="Richard Yu"
student_github="https://github.com/richard5805"

[[mentored.student_project]]
start_new_row=true
link="https://2131790781.github.io/simluator-project-website/"
name="Escape from Emergency Simulator"
image="/assets/images/fire-emergency.png"
alt="Fire Emergency Level"
summary="A 3D first person simulation game that can be used to teach others how to react in an emergency situation, such as a fire."
org="coding-minds"
student="Congyu Zhao"
student_page="https://2131790781.itch.io/"
student_github="https://github.com/2131790781"

[[mentored.student_project]]
link="https://sites.google.com/view/horde-zombie-survival/home"
name="Horde"
image="https://img.itch.zone/aW1hZ2UvMTA2MTYxNS85NzE5NTEyLnBuZw==/original/m0YLN9.png"
alt="Horde screenshot"
summary="A 2D multiplayer co-op survival game where one is tasked with killing all the zombies and escaping with friends. Avilable on <a href='https://da-bank.itch.io/horde'>Itch.io</a>"
org="coding-minds"
student="Billy Hsu"
student_page="https://da-bank.itch.io"

[[mentored.student_project]]
link="https://g47god3.itch.io/dungeon-project-summer-2021"
name="Dungeon Project 1"
image="/assets/images/dungeon.png"
alt="Dungeon Game Screenshot"
summary="A 2D top-down shooter game where one has to kill all the enemies inside the level."
org="coding-minds"
student="Gary Wang"
student_page="https://g47god3.itch.io"

[[mentored.student_project]]
link="https://jasonzhu.itch.io/clean-up-crew"
name="Clean Up Crew"
image="/assets/images/agent-cleanup.png"
alt="Agent #2"
summary="A simple 3D game where one is tasked with controlling robots to move boxes from one area to the scoring zone."
org="coding-minds"
student="Jason Zhu"
student_page="https://jasonzhu.itch.io"