title = "Projects"
date = "2023-11-05"
summary = "A list of projects I have worked on."
layout = "layouts/website/components/projects_list.vto"

#gallery_template: "gallery.html"
page_template = "project-page.html"
section_template = "projects-section.html"

sort_by_weight = true