layout = "layout.vto"
author = "Suraj S. Singh"
lang = "en-US"
description = "Explore Suraj S Singh's projects" 
keywords = "portfolio, projects, unity, c#"
assets = "/assets"

base_url = "https://surajssingh.com"
linkedin = "Suraj-S-Singh"

[metas]
type = "website"
site = "Suraj S Singh's Website"
title = "=title || $ h1 || =site"
lang = "=lang"
description = "=summary || =description"
image = "=cover_image.file || =image"
color = ["#136d0d", "#69c133"]
generator = true

[license]
name = "CC BY-ND 4.0"
link = "https://https://creativecommons.org/licenses/by-nd/4.0/"
full = " Creative Commons Attribution-NoDerivatives 4.0 International"
icon = '<img style="height:20px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:20px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:20px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1" alt=""></a>'

[data_default]
image_height = 300

[[header_nav]]
name="Projects"
link="/project"

[[header_nav]]
name="Skills"
link="/skills"

[[header_nav]]
name="About"
link="/about"

[[top_skills]]
name="Unity"
id="unity"
homepage="https://unity.com"
icon="images/skills/unity-color.svg"

[[top_skills]]
name="C#"
id="cs"
homepage="https://learn.microsoft.com/en-us/dotnet/csharp/"
icon="images/skills/csharp-color.svg"

[[top_skills]]
name="Rust"
id="rust"
homepage="https://www.rust-lang.org/"
icon="images/skills/rust-color.svg"

[[top_skills]]
name="Python"
id="py"
homepage="https://www.python.org/"
icon="images/skills/python-color.svg"

[[top_skills]]
name="TypeScript"
id="ts"
homepage="https://www.typescriptlang.org/"
icon="images/skills/typescript-color.svg"

[[top_skills]]
name="Svelte"
id="svelte"
homepage="https://svelte.dev/"
icon="images/skills/svelte-color.svg"

[footer]
ssg = {name = "Lume", link = "https://lume.land"}

[[footer.nav]]
name="Blog"
link="https://surajssingh.github.io/Tech-Tree-Blog/"

[[footer.nav]]
name="GitHub"
link="https://github.com/SurajSSingh"

[[footer.nav]]
name="LinkedIn"
link="https://www.linkedin.com/in/suraj-s-singh/"

[[footer.stylings]]
name = "Chota"
link = "https://jenil.github.io/chota/"

[[footer.stylings]]
name = "Skill Icons"
link = "https://skillicons.dev"

[[footer.stylings]]
name = "Simple Icons"
link = "https://simpleicons.org"